version: "3.7"
services:
    pyapi:
        container_name: pyapi
        build:
            context: .
            dockerfile: ./services/pyapi/Dockerfile
            args:
                PASSWORD: pass
                UNAME: bdb
                HOSTNAME: romiq
        expose:
            - 5000
    shinyapp:
        container_name: shinyapp
        build:
            context: .
            dockerfile: ./services/shinyapp/Dockerfile
            args:
                PASSWORD: pass
                UNAME: bdb
        restart: unless-stopped
        ports:
            - 3838:3838
