apiVersion: v1
kind: Service
metadata:
    name: pyapi
    labels:
        service: pyapi
        env: dev
spec:
    selector:
        app: pyapi
    ports:
    - port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: pyapi 
    labels:
        env: dev
spec:
    selector:
        matchLabels:
            app: pyapi
    replicas: 3
    template:
        metadata:
            labels:
                app: pyapi
        spec:
            containers:
            - name: pyapi
              image: sktrinh12/romiq-ctnr:latest
              env:
              - name: UNAME
                value: bdb
              - name: PASSWORD
                value: pass
              - name: VERSION
                value: "1_2_1b"
            restartPolicy: Always
