FROM sktrinh12/meta-shinybase:latest

ARG UNAME
ARG PASSWORD
ENV UNAME $UNAME
ENV APP_HOME "/home/${UNAME}"
ENV PASSWORD $PASSWORD

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean

RUN useradd -m -d $APP_HOME "${UNAME}" \
    && chown -R ${UNAME}:${UNAME} $APP_HOME \
    && echo "${UNAME}:${PASSWORD}" | chpasswd

# set up git ssh
USER $UNAME
RUN mkdir -p $APP_HOME/.ssh/
COPY services/romiq/azdevops $APP_HOME/.ssh/id_rsa
RUN ssh-keyscan ssh.dev.azure.com >> $APP_HOME/.ssh/known_hosts

# # git clone shiny app
RUN mkdir $APP_HOME/app \
    && git clone -b no-pgdb --single-branch git@ssh.dev.azure.com:v3/SpencerTrinh/meta-shiny-app/meta-shiny-app $APP_HOME/app

# COPY services/shinyapp/app $APP_HOME/app

# change ownership to UNAME
USER root
RUN chown -R $UNAME:$UNAME $APP_HOME

EXPOSE 3838

CMD ["R", "-e", "shiny::runApp('/home/bdb/app', host= '0.0.0.0', port = 3838)"]
